name       : mpvpaper
version    : 1.8
release    : 1
source     :
    - https://github.com/GhostNaN/mpvpaper/archive/refs/tags/1.8.tar.gz : 1354b3a2ed05bca38b61cfecaaddc2a38bc203719a27e3805928c2997840606d
homepage   : https://github.com/GhostNaN/mpvpaper
license    : License_Goes_Here (e.g., MIT, GPL-3.0-or-later)
summary    : Un programa de fondo de pantalla de video para compositores Wayland basados en wlroots.
component  : multimedia.utils
description: |
    mpvpaper es un programa de fondo de pantalla para compositores Wayland basados en wlroots,
    como Sway, que permite reproducir videos con mpv como fondo de pantalla.
builddeps  :
    - mpv-libs
    - meson
    - ninja
rundeps    :
    - mpv
    - wlroots
setup      : |
    %meson
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Instalación manual del manpage si no lo hace meson automáticamente
    install -vDm0644 mpvpaper.man %{buildroot}/usr/share/man/man1/mpvpaper.1
    # Opcional: Instalar el archivo man si existe
    # install -D -m 00644 mpvpaper.1 $installdir/usr/share/man/man1/mpvpaper.1
